ANNO:
  PARSER: 'labelimg'
  CREATOR: 'yolov5'
INPUT:
  DIR: 'tests/labelimg_2_yolov5/'
  IMAGE_FOLDER: 'data-labelimg'
  LABEL_FOLDER: 'data-labelimg'
OUTPUT:
  DIR: 'tests/labelimg_2_yolov5/data-yolov5/'
LABELIMG:
  IMG_EXTENSION: '.png'
  ANNO_EXTENSION: '.xml'
YOLOV5:
  IMG_EXTENSION: '.png'
  ANNO_EXTENSION: '.txt'