ANNO:
  PARSER: 'visdrone'
  CREATOR: 'tlt'
INPUT:
  DIR: 'tests/visdrone_2_tlt/data-virdrone/'
  IMAGE_FOLDER: 'images'
  LABEL_FOLDER: 'annotations'
OUTPUT:
  DIR: 'tests/visdrone_2_tlt/data-tlt/'
VISDRONE:
  IMG_EXTENSION: '.jpg'
  ANNO_EXTENSION: '.txt'
TLT:
  IMG_EXTENSION: '.jpg'
  ANNO_EXTENSION: '.txt'